title: "Justin Walker"
author: ""
description: "WEB DEVELOPER, CAT ENTHUSIAST, FAN OF VINTAGE COCKTAILS, TRAVEL, AND BREAKFAST BURRITOS"

# Jekyll settings
permalink: pretty         # see https://jekyllrb.com/docs/permalinks/
paginate: 5                  # number of articles per page, remove to disable pagination
excerpt_separator: <!--more-->  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode
# Theme Source: https://github.com/niklasbuschmann/contrast

navigation:                  # (optional) site navigation in the header
  - index.html
  - projects.md
  - archive.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:"
#  github: "https://github.com"
  rss: "/feed.xml"

comments:                    # embed disqus or isso comments
  disqus: "justindwalker"
#  isso: ""

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
